# Continuos Integration workflow

name: CI trigger test

defaults:
  run:
    shell: bash -ieo pipefail {0}

# Controls when the workflow will run
on:
  # Main push
  push:
    branches: ['skip-crawler-on-autoupdate']

  # Can be triggered by other workflows
  workflow_call:

  # Allow manual trigger
  workflow_dispatch:

# Jobs
jobs:

  # Call CI
  ci-check:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

# EOF
