# Continuos Integration workflow

name: CI

defaults:
  run:
    shell: bash -ieo pipefail {0}

# Controls when the workflow will run
on:

  # Main push
  push:
    branches: ['ci_fix']

  # Allow manual trigger
  workflow_dispatch:

# Jobs
jobs:

  webpack:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate production bundle
        run:  npm ci && npm run build && npm run pack

# EOF
